services:
    main:
        build: ./server
        volumes:
            - ./server:/src
            - deps:/src/node_modules
        depends_on:
            - mongo
        networks:
            - mongo_net
        ports:
            - 3000:3000
        environment:
            - MONGO_URL=mongodb://admin:password12341234@mongo:27017/pet_tracker?authSource=admin
            - PORT=3000
            - DEV_MODE=${DEV_MODE}
            - SWAGGER_HOST=${SWAGGER_HOST}
            - SWAGGER_SCHEMA=${SWAGGER_SCHEMA}
            - JWT_SECRET_ACCESS=dGqbwCF1lbn9zXk77SsuiCWYxnR6nJCg
            - JWT_SECRET_REFRESH=XkAYI2bqUmT2yHOaCqCOYq5QCtvP2NwO
            - SESSION_EXP_TIME=25920000
            - JWT_ACCESS_EXP=3h
            - JWT_REFRESH_EXP=3d
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        command: sh -c "if [ "$DEV_MODE" = "false" ]; then npm start; else npm run test; npm run swagger && npm run dev; fi"
    mongo:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password12341234
        volumes:
            - mongo_data:/data/db
        networks:
            - mongo_net
        ports:
            - "27017:27017"

networks:
    mongo_net:

volumes:
    mongo_data:
    deps:
