# Base image
FROM node:24-alpine3.21

# Set working directory inside container
WORKDIR /src

# Copy only necessary files
COPY package*.json ./
RUN npm install

# Copy the rest of the server code into /src
COPY . .

# Start the app using nodemon
CMD ["npm", "run", "dev"]
